backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\Html;
use app\models\LoginForm;
use app\models\UploadForm;
use yii\web\UploadedFile;   
use app\models\User;
use app\models\Arrears;
use app\models\Loan;
use app\models\Banks;
use app\models\Config;
use app\models\BankClient;
use app\models\Clients;
use app\models\ClientInvitation;
use app\models\RegisteredRequests;
use app\models\GeneratedRequests;
use app\models\Status;
use frontend\models\CommissionRound;
use frontend\models\Commission;
use frontend\models\LoanQuota;
use yii\helpers\ArrayHelper;

/**
 * Site controller
 */
class SiteController extends Controller
{        
        
    /**
     * @inheritdoc
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error',],
                        'allow' => true,
                        'roles' => ['?'],                                                 
                    ],
                    [
                        'actions' => ['index','logout','solicitudes','liquidaciones-prestamos',
                                      'cartera-credito','cuotas-carteras','registro-liquidaciones',
                                      'mostrar-solicitudes','custom-search','registro-solicitantes',
				      'match-liquidaciones'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],                                        
                ],
                
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
  
    /**
     * @inheritdoc
     */
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    public function actionIndex(){
      
      $modelLoan = new Loan();      
      $modelClient = new Clients();
      $modelArrears = new Arrears();
      $modelClientInvi = new ClientInvitation();

      // cantidad de ahijados
      $ahijCount = $modelClient->findClientsCount();      

      // Cantidad de hombres
      $mCount = $modelClient->findCountByGender(Yii::$app->params['genderM']);            

      // Cantidad de mujeres
      $fCount = $modelClient->findCountByGender(Yii::$app->params['genderF']);      
      
      /**
       * ACTIVOS (Todos Vigentes, Vencidos, Mora)
       */            
      $pActivosSum = $modelLoan->getSumAllByStatus(
        [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      $pActivosAmbos = $modelLoan->findCountByGenderStatus(
        [ Yii::$app->params["genderM"],
          Yii::$app->params["genderF"] ],
        [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      $pActivosHombres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params['genderM'],
        [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      $pActivosMujeres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params['genderF'],
        [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      $pAMontosHombres = $modelLoan->getSumAmountByGender(
          Yii::$app->params['genderM'],
          [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      $pAMontosMujeres = $modelLoan->getSumAmountByGender(
          Yii::$app->params['genderF'],
          [ Yii::$app->params['status_vigente'],
          Yii::$app->params['status_vencido'],
          Yii::$app->params['status_mora'] ]
      );

      /**
       * AL DIA (Solo Vigentes)
       */            
      $pAlDiaSum = $modelLoan->getSumAllByStatus(Yii::$app->params['status_vigente']);

      $pAlDiaAmbos = $modelLoan->findCountByGenderStatus(
        [ Yii::$app->params['genderM'],
          Yii::$app->params['genderF'] ],
        Yii::$app->params['status_vigente']
      );

      $pAlDiaHombres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params["genderM"],
        Yii::$app->params['status_vigente']          
      );

      $pAlDiaMujeres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params["genderF"],
        Yii::$app->params['status_vigente']
      );

      $pADMontosHombres = $modelLoan->getSumAmountByGender(
          Yii::$app->params["genderM"],
          Yii::$app->params['status_vigente']          
      );

      $pADMontosMujeres = $modelLoan->getSumAmountByGender(
          Yii::$app->params["genderF"],
          Yii::$app->params['status_vigente']          
      );

      /**
       * MORA (Solo en Mora)
       */
      $pMoraSum = $modelArrears->getSumMoraAllByGender(
        [ Yii::$app->params['genderM'],
          Yii::$app->params['genderF'] ]
      );

      $pMoraAmbos = $modelLoan->findCountByGenderStatus(
        [ Yii::$app->params['genderM'],
          Yii::$app->params['genderF'] ],
        Yii::$app->params['status_mora']
      );

      $pMoraHombres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params["genderM"],
        Yii::$app->params['status_mora']        
      );

      $pMoraMujeres = $modelLoan->findCountByGenderStatus(
        Yii::$app->params["genderF"],
        Yii::$app->params['status_mora']
      );

      $pMOMontosHombres = $modelArrears->getSumMoraAllByGender(Yii::$app->params["genderM"]);

      $pMOMontosMujeres = $modelArrears->getSumMoraAllByGender(Yii::$app->params["genderF"]);    
  
      /**
       * SOLICITUDES ACUMULADAS / MES / HOY
       */            
      $sumHoy = $modelLoan->getRequestByToday();
      
      // Suma de las Solicitudes del Mes
      $month = date('m');              
      $sumMes = $modelLoan->getRequestByMonth($month);
      
      // Suma de las Solicitudes Totales
      $sumAcumuladas = $modelLoan->getRequestByAll();
                  
      return $this->render('index',[
        'ahijCount' => $ahijCount,
        'mCount' => $mCount,
        'fCount' => $fCount,
        'sumActivos' => $pActivosSum,
        'ambosActivos' => $pActivosAmbos,
        'hombresActivos' => $pActivosHombres,
        'mujeresActivas' => $pActivosMujeres,
        'montoHombresActivos' => $pAMontosHombres,
        'montoMujeresActivas' => $pAMontosMujeres,        
        'sumAlDia' => $pAlDiaSum,
        'ambosAlDia' => $pAlDiaAmbos,
        'hombresAlDia' => $pAlDiaHombres,
        'mujeresAlDia' => $pAlDiaMujeres,
        'montoHombresAlDia' => $pADMontosHombres,
        'montoMujeresAlDia' => $pADMontosMujeres,              
        'sumMora'=>$pMoraSum,
        'ambosMora' => $pMoraAmbos,
        'hombresMora' => $pMoraHombres,
        'mujeresMora' => $pMoraMujeres,
        'montoHombresMora' => $pMOMontosHombres,
        'montoMujeresMora' => $pMOMontosMujeres,        
        'sToday' => $sumHoy,
        'sMonth' => $sumMes,
        'sAcumulate' => $sumAcumuladas        
      ]);        
    }

    public function actionLogin(){                        

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();  
        
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {                                                              
            return $this->goBack();        
        } else {        
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout(){
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    /**
     * Se encarga de redireccionar a la vista 
     * para mostrar las solicitudes de prestamo 
     * que se han generado en el sistema
     */ 
    public function actionSolicitudes(){    
        
        $modelRRequest = new RegisteredRequests();        
        $modelGRequest = new GeneratedRequests();

        // dataProvider de tabla Loan
        $dataProvider = new ActiveDataProvider([
            'query' => Loan::find(),                        
     	    'sort' => [
                    'defaultOrder' => [
                        'date_add' => SORT_DESC,
                    ]
            ],
        ]);

        // dataProvider tabla Registered_request
        $dataProviderRR = new ActiveDataProvider([
                    'query' => RegisteredRequests::find()
                                                ->where(['registered'=>true]),                        
                    'sort' => [
                        'defaultOrder' => [
                            'date_request' => SORT_DESC,                
                        ]
                    ],
        ]);

        
                    
        return $this->render('solicitudes', [
            'dataProvider'  => $dataProvider,                                
            'modelRRequest' => $modelRRequest,
            'modelGRequest' => $modelGRequest,
            'dataProviderRR'=> $dataProviderRR
        ]);                
    }       
    
    /**
     * Encargado de mostrar todas las solicitudes
     * generadas en el dia y tambien permite mostrar 
     * los status de cada una de estas solicitudes
     */ 
    public function actionLiquidacionesPrestamos(){                 
        

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use frontend\models\Loan;
use frontend\models\login\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\ClientInvitation;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\ResetPass;
use  yii\web\Session;



/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = "site";
    /**
     * @inheritdoc
     */
  

    public function behaviors()
    {        
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login','password-reset-step1','password-reset-step2'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => [
                                        'logout','index','faq','invitacion','sistema-grafico',
                                        'sistema','pago-cancelaciones','calendario','rapidez-confianza',
                                        'oportunidades','error','contact','captcha'
                                    ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            
        ];
    }


    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

/*
    public function beforeAction($action)
    {
        //if(\Yii::$app->user->isGuest)
         //   return $this->redirect(['site/login']);
        

        return true;
        
    }
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex($alert=false)
    {

        return $this->render('index',['alert'=>$alert]);
    }

    public function actionFaq(){
        return $this->render('preguntas');
    }
    public function actionInvitacion(){
        return $this->render('invitacion');
    }
    public function actionSistema(){
        return $this->render('sistema');
    }
    public function actionPagoCancelaciones(){
        return $this->render('pagos');
    }
    public function actionCalendario(){
        return $this->render('calendario');
    }
    public function actionSistemaGrafico(){
        return $this->render('sistemagrafico');
    }
    public function actionRapidezConfianza(){
        return $this->render('rapidez');
    }
    public function actionOportunidades(){
        return $this->render('oportunidades');
    }





    public function actionLogin()
    {
        $this->layout = 'nomain';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            return $this->redirect(['site/index', 'alert'=>$this->alertVerifid()]);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }

    }
    
    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionPasswordResetStep1()
    {
        $this->layout = 'resetPass';

        $model = new ResetPass(['scenario'=>'step1']);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $newmodel = new ResetPass(['scenario'=>'step2']);
            $session = new Session;
            $session->open();
            $session['email'] =$model->email;

            return $this->redirect(['site/password-reset-step2']);


        }

        return $this->render('resetStep1', [
            'model' => $model,
        ]);
    }
    public function actionPasswordResetStep2(){
        $this->layout = 'resetPass';
        $model = new ResetPass(['scenario'=>'step2']);
        $model->email = Yii::$app->session['email'];
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                
                if ($model->sendEmail()) {
                    Yii::$app->session->setFlash('success', 'Una nueva contraseña fue enviada a su correo.');
                    return $this->redirect(['site/login']);
                }
                else {
                    Yii::$app->session->setFlash('error', 'Lo sentimos, No pudimos enviarte una nueva contraseña.');
                }
            }

        return $this->render('resetStep2', [
            'model' => $model,
        ]);
    }


    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token){
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    private function alertVerifid(){
       $id=Yii::$app->user->identity->id;
       $exist = Loan::find()->where(['id_client'=>$id, 'id_status'=>[42,43]])->exists();
       return $exist;
    }
    
    public function actionContact()
    {
        $model = new ContactForm();
        $model->name =Yii::$app->user->identity->Shortname();
        $model->email = Yii::$app->user->identity->email;
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/calendario.php
<?php
use yii\helpers\Html;

$this->title = 'Sistema Padrino | Tupadrino.net';
?>

<style type="text/css">
.wrap{
	background: url(<?=Yii::$app->request->baseUrl?>/img/deco/calendario.png);
	background-repeat: no-repeat;
	background-size:24%;
	background-position: 101% 100%;
}
</style>
	
<div class="site-content info-content2">
	<h2 class="titulo-seccion green">
		<?=	Html::img('@web/img/site/calendarioIco.png',['height' =>'45']) ?>
		Calendario Bancario
	</h2>
	<div class="wrap-site-calendario">
		<?=	Html::img('@web/img/site/calendario.png',['class' => 'img-responsive','style'=>'background:#FFF']) ?>
	</div>
</div>

frontend/views/site/clients.php
<?php
echo '<h1>OLA K ACE</h1>';
?>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
if (!Yii::$app->user->isGuest) {
    $this->context->layout = 'main';
}
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'Inicio | Tupadrino.net';

$this->registerJsFile(Yii::$app->request->baseUrl.'/js/site-index.js',[
    'depends' => [\yii\web\JqueryAsset::className()]
    ]); 


$html='	<div class="alert-overlay">
		<div class="alert-message col-lg-6 col-lg-offset-3">
			<p>
				Estimado(a):<br>
				<strong>'.Yii::$app->user->identity->Shortname().'</strong>
				<br>
			</p>
			<div class="alert-message-body">
				<p>
					Actualmente tienes compromiso(s) pendiente(s) de pago. Si ya realizaste
					el pago, recuerda registrarlo en: MI CUENTA/PAGOS/REGISTRAR
				</p>

				<p>
					Recuerda mantener al día tus compromisos según lo hayas convenido
					desde el inicio del proceso. Este sistema está basado en la confianza
					entre el Padrino y sus Ahijados, tu comportamiento puede afectar los
					beneficios y reputación de quienes te dieron la oportunidad de acceder a
					nuestro sistema
				<p>
			</div>
			<p class="text-center">
		      '.Html::a("Continuar", ["credito/vigente"], ["class" => "btn btn-arrow"]).'
		   </p>
		</div>
	</div>'
?>
<style type="text/css">
	
	.carousel-indicators{
		display: none;
	}
</style>

	<?= $alert?$html:'' ?>

<div class="site-index">

   <div class="body-content">
	   <br>
	   <br>
		<div id="carousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<video id="video1" controls class="img-responsive center-block">
		    			<source src="<?= Yii::$app->request->baseUrl.'/video/TuPadrino.mp4'?>" type="video/mp4">
		    			Tu navegador no soporta videos HTML5.
		  			</video>
	  			</div>
			    <div class="item">
			    	<?=	Html::img('@web/img/site/banners/banner1.png',['class' => 'img-responsive']) ?>
			    </div>
			    <div class="item">
			    	<?=	Html::img('@web/img/site/banners/banner2.png',['class' => 'img-responsive']) ?>
			    </div>
			    <div class="item">
			    	<?=	Html::img('@web/img/site/banners/banner3.png',['class' => 'img-responsive']) ?>
			    </div>
			</div>
		</div>
		<br>
		<br>

		<div class="row site-index-icon">
			<div class="col-md-2 col-xs-6 icon  col-md-offset-1">
				<a href="<?= Url::to(['site/sistema-grafico'])?>">
					<div class="imagen">
					<?=	Html::img('@web/img/site/sistema.png',['height'=>76]) ?>
					</div>
					<div class="text">Sistema Padrino</div>
				</a>
			</div>
			<div class="col-md-2 col-xs-6 icon">
				<a href="<?= Url::to(['site/oportunidades'])?>">
					<div class="imagen">
					<?=	Html::img('@web/img/site/oportunidades.png',['height'=>76]) ?>
					</div>
					<div class="text">Oportunidades</div>
				</a>
			</div>
			<div class="col-md-2 col-xs-6 icon">
				<a href="<?= Url::to(['site/rapidez-confianza'])?>">
					<div class="imagen">
					<?=	Html::img('@web/img/site/rapidez.png',['height'=>76]) ?>
					</div>
					<div class="text">Rapidez-Confianza</div>
				</a>
			</div>	
			<div class="col-md-2 col-xs-6 icon">
				<a href="<?= Url::to(['site/pago-cancelaciones'])?>">
					<div class="imagen">
					<?=	Html::img('@web/img/site/pago.png',['height'=>76]) ?>
					</div>
					<div class="text">Responsabilidad y compromiso</div>
				</a>
			</div>	
			<div class="col-md-2 col-xs-6 icon">
				<a href="<?= Url::to(['site/faq'])?>">
					<div class="imagen">
					<?=	Html::img('@web/img/site/faq.png',['height'=>60,]) ?>
					</div>
					<div class="text">Preguntas frecuentes</div>
				</a>
			</div>

		</div>
	</div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'TuPadrino.net';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>
<style type="text/css">
    body{
        color:#6e6f73;
        background: url(<?=Yii::$app->request->baseUrl?>/img/deco/login.png);
        background-repeat: no-repeat;
        background-size:25%;
        background-position: 100% 100%;
    }
</style>

<div class="site-login">


    <div class="row">
        <?php
            foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
                echo '<div class="alert alert-' . $key . '">' . $message . '</div>';
            }
        ?>
        <div class="col-lg-4 col-lg-offset-4 text-center">
            <?= Html::img('@web/img/logo.png', ['width'=>350, 'alt'=>Yii::$app->name, 'class'=>'img-responsive']) ?>
            <br>
            <br>
            <h1 class="titulo-seccion">
                 <?= Html::img('@web/img/hola.png', ['width'=>55, 'alt'=>Yii::$app->name,]) ?>
            ¡Bienvenido!
            </h1>
            <br>
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form
                    ->field($model, 'email',$fieldOptions1 )
                    ->label(false)
                    ->textInput(['placeholder' => $model->getAttributeLabel('email')])
                ?>
                <br>
                <?= $form
                    ->field($model, 'password',$fieldOptions2)
                    ->label(false)
                    ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) 
                ?>

                <div class='text-right' style="color:#0da0c2;margin:1em 0;">
                    <?= Html::a('¿Olvidó su contraseña?', ['site/password-reset-step1']) ?>
                </div>
                <br>
                <br>
                <div class="form-group">
                    <?= Html::submitButton('Entrar', ['class' => 'btn btn-arrow', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/pagos.php
<?php
use yii\helpers\Html;
use frontend\models\SystemBankAccount;

$this->title = 'Sistema Padrino | Tupadrino.net';

?>

<style type="text/css">
.wrap{
	background: url(<?=Yii::$app->request->baseUrl?>/img/deco/pagos.png);
	background-repeat: no-repeat;
	background-size:40%;
	background-position: 101% 101%;
}
</style>
	
<div class="site-content info-content">
	<h2 class="titulo-seccion green">
		<?=	Html::img('@web/img/site/cancelaciones.png',['height' =>'45']) ?>
		 Responsabilidad y Compromiso
	</h2>
	<div class="wrap-site-content"  style="padding-left:7%">
		<p> Recuerda mantener al día tus compromisos a principio de cada mes o según lo 
		hayas convenido desde el inicio del proceso. Este sistema está basado en la confianza
		 entre el Padrino y sus Ahijados, tu comportamiento puede afectar los beneficios y 
		 reputación de quienes te dieron la oportunidad de acceder a nuestro sistema. 
		</p>

		<p>
		Para ayudar a fortalecer nuestro vinculo, a continuación te colocamos nuestros datos para 
		el momento de realizar tus pagos por los compromisos adquiridos:
		</p>

		<div class="payment-type">
			<strong>Para depósitos y transferencias:</strong> 
			<div class="payment-type-content">
				<?= SystemBankAccount::getHtmlAccounts()?>

			</div>
		</div>
		<div class="payment-type">
			<strong>Para pagos con Tarjeta de Crédito:</strong>
			<div class="payment-type-content">
				<p>Directamente en <?= Html::a('tupadrino.net', ['record-payment/create']) ?>
			</div>
		</div>
	</div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetStep1.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '¿Olvidó su contraseña?';
?>
<style type="text/css">
    body{
        color:#6e6f73;
        background: url(<?=Yii::$app->request->baseUrl?>/img/deco/login.png);
        background-repeat: no-repeat;
        background-size:25%;
        background-position: 100% 100%;
    }
</style>
<div class="site-request-password-reset text-center">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor ingrese su correo electronico de acceso al sistema.<p>

    <div class="row">
        <div class="col-lg-6  col-lg-offset-3 ">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->label(false) ?>

                <div class="form-group">
                    <?= Html::submitButton('Siguiente', ['class' => 'btn btn-arrow']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>